name = "MAT120"
version = "0.1.0"
defaultTargets = ["MAT120"]

[[lean_lib]]
name = "MAT120"

[[require]]
name = "verbose"
git = "https://github.com/PatrickMassot/verbose-lean4.git"
rev = "a2f87b133d5b5e1b0b81d4fd7586b8750c08c5db"
